SUBROUTINE TRANS_MATRIX(A,B,M,N)
INTEGER:: M,N
DOUBLE PRECISION:: A(M,N),B(N,M)
DOUBLE PRECISION:: C(N,M)
INTEGER::I,J
DO I=1,M
  DO J=1,N
    C(J,I)=A(I,J)
  ENDDO
ENDDO
B=C
RETURN
END SUBROUTINE TRANS_MATRIX
